### ISSUE TITLE
Repository name and structure

### ISSUE THREAD

**Issue by aleh-churak2** [Muhammad752/LeverX-lab#1]
I expected that Module_1 would be the folder inside the repository that contains screenshots. And the name of the repository is - any ("LeverX-lab" for example).

Example:
<img width="141" alt="image" src="https://user-images.githubusercontent.com/99028819/226917595-c8648adc-f163-4175-ac04-faf065a0ecac.png">

**Comment by Muhammad752** [comment]
Yeah I got you, now corrected
